### ISSUE TITLE
[Question] Are there plans to open source markbench itself?

### ISSUE THREAD

**Issue by regner** [LTTLabsOSS/markbench-tests#10]
First of all: Thank you for open sourcing what you have! It's wonderful to see the work being shared.

I was wondering if there was intention to open source the markbench tool itself. Having reviewed the code in this repo I would love to contribute, but without markbench being available it will be very hard to ensure changes don't break compatability. At the very least it would be great to get some kind of documentation, or test cases, which help make sure that interface isn't broken.

Again, thanks for open sourcing this repo. I look forward to what else your team has in store. :)

**Comment by regner** [comment]
I have a few more questions. Going to drop them here as I don't want to spam a whole bunch of issues.

The `pyproject.toml` contains reference to some pytests, but there does not appear to be any in the repo. Do those exist? If so are there plans to include them?

Is there a place that discussion for this is preffered? Would you prefer discussion in GitHub issues or somewhere else?

**Comment by nharris-lmg** [comment]
We do aim to open source as much as we can, and we do wish it were easy to plop the code on GitHub and call it a day, however it's never so simple. As our team grows we will be able to support the community much better.

The test harnesses in this repo used to reside in the same repository as the source for the MarkBench client. We tried our best to eliminate old references, but the pytests reference you found seems to be a culprit we missed.

Here as an issue, or on the forum are the preferred places for discussions like this. Discussions are much more visible to our inboxes here, than the forums (unless @'d).

**Comment by nharris-lmg** [comment]
Closing this, but if you have more questions, add here, or open a new issue.
