### ISSUE TITLE
[Bug] Documentation error for linking CODE_OF_CONDUCT

### ISSUE THREAD

**Issue by chomes** [LTTLabsOSS/markbench-tests#6]
## Problem
When viewing the `CONTRIBUTE.md` you provide a link to your `CODE_OF_CONDUCT.md` file however this link is incorrect.

This link points to: https://github.com/LTTLabsOSS/markbench-tests/blob/main/blob/master/CODE_OF_CONDUCT.m
The branch master doesn't exist, it should point to: https://github.com/LTTLabsOSS/markbench-tests/blob/main/CODE_OF_CONDUCT.md

## Expected resolution
Change to https://github.com/LTTLabsOSS/markbench-tests/blob/main/CODE_OF_CONDUCT.md

**Comment by nharris-lmg** [comment]
This has been looked after.
