### ISSUE TITLE
[Bug/Question] 

### ISSUE THREAD

**Issue by TesterTim** [LTTLabsOSS/markbench-tests#60]
### Environment

```markdown
- MarkBench Test Version: 1.0.0
- OS: Win 11 22H2
- GPU: RX 6650M
- CPU: Ryzen 7 6800H
```

### What happened?

When running python .\msikombuster.py --test vkfurrytorus --resolution "1080,1920" -b true , it will launch with iGPU instead of dGPU. What do I need to do to ensure that it always launches with the correct GPU? When going into device manager and disabling the iGPU, only then will it launch with the dGPU. Please help :P

**Comment by nharris-lmg** [comment]
This is a limitation of the aging harness which is our MSI Kombustor test. You can select which GPU device to use if you run Kombustor from its GUI.
