### ISSUE TITLE
[Feature Request] Consider releasing precompiled / pre-packaged executable

### ISSUE THREAD

**Issue by HunterAP23** [LTTLabsOSS/markbench-tests#9]
For more general users who aren't familiar with programming or even the command line, a single executable file would simplify the launch process for these people.

There are a few solutions to this, such as:
- Use the `pyinstaller` program to generate the executable. It may take a bit of work to get the proper files and dependences packaged into the executable, but it is relatively straightforward.
- Use the `py2exe` program. Similar to `pyinstaller`
- Use the `Nuitka` program to compile and package the code. Whereas the prior two solutions package the python code and an entire python runtime into a single executable, `Nuitka` instead compiles portions of the code down to C for a decent gain in performance (depending on the workload). This may take more work than either of the other solutions, but it'll make the overall program performance much better on top of being packaged into an executable.

You may also consider creating GitHub Actions to automate this compiling / packaging / releasing process.

**Comment by nharris-lmg** [comment]
Thank you for your suggestion! The MarkBench desktop client is a single file (more-or-less) as a good portion of it is Golang compiled down into an executable.  We do want anyone to be able to run our test harnesses and make it as frictionless as possible to get started.
